---
# Block device where partition table will be created.
partition_layout_device: /dev/vda

# List of partitions to create on the target device.
# - Start at 1MiB to reserve space for GPT and ensure alignment.
# - 260MiB ESP: 4MiB-aligned size above FAT32's ~256MiB minimum (ref: https://superuser.com/a/1717643).
partition_layout_table:
  - device: "{{ partition_layout_device }}"
    number: 1
    start: 1MiB
    end: 261MiB
    flags:
      - esp
      - boot

  - device: "{{ partition_layout_device }}"
    number: 2
    start: 261MiB
    end: 100%
    flags:
      - lvm

# List of filesystems to create.
partition_layout_filesystems:
  - type: vfat
    device: "{{ (partition_layout_device, 1) | join_device_partition }}"
    options: -F32
  - type: lvm
    device: "{{ (partition_layout_device, 2) | join_device_partition }}"
