---
- name: Configure partitions
  hosts: all
  become: true
  roles:
    - partition
  vars_prompt:
    - name: partition_layout_device
      prompt: Enter the target device for partitioning
      private: false

    - name: partition_lvm_group_name
      prompt: Enter the name of the main LVM volume group
      private: false
