---
- name: Enable systemd-homed
  ansible.builtin.systemd_service:
    name: systemd-homed
    state: started
    enabled: true

- name: Inspect user
  register: user_inspect_result
  failed_when: false
  changed_when: false
  ansible.builtin.command:
    cmd: "/usr/bin/homectl inspect {{ user_name }}"

- name: Add or update user
  block:
    - name: Add user
      when: user_inspect_result.rc == 1
      environment:
        NEWPASSWORD: "{{ user_password }}"
      ansible.builtin.command:
        argv:
          - /usr/bin/homectl
          - create
          - "{{ user_name }}"
          - "--ssh-authorized-keys={{ user_ssh_keys | join(',') }}"
          - "--luks-offline-discard={{ user_storage_luks_offline_discard }}"
          - "--luks-discard={{ user_storage_luks_discard }}"
          - "--member-of={{ user_groups | join(',') }}"
          - "--disk-size={{ user_disk_size }}"
          - "--fs-type={{ user_filesystem }}"
          - "--storage={{ user_storage }}"
          - "--shell={{ user_shell }}"

    - name: Update user
      when: user_inspect_result.rc == 0
      environment:
        PASSWORD: "{{ user_password }}"
      ansible.builtin.command:
        argv:
          - /usr/bin/homectl
          - update
          - "{{ user_name }}"
          - "--ssh-authorized-keys={{ user_ssh_keys | join(',') }}"
          - "--luks-offline-discard={{ user_storage_luks_offline_discard }}"
          - "--luks-discard={{ user_storage_luks_discard }}"
          - "--member-of={{ user_groups | reject('equalto', omit) | join(',') }}"
          - "--disk-size={{ user_disk_size }}"
          - "--fs-type={{ user_filesystem }}"
          - "--storage={{ user_storage }}"
          - "--shell={{ user_shell }}"
