---
- name: Configure packages
  tags: package
  ansible.builtin.include_tasks:
    file: package.yaml
    apply:
      tags: package

- name: Configure time
  tags: time
  ansible.builtin.include_tasks:
    file: time.yaml
    apply:
      tags: time

- name: Configure locale
  tags: locale
  ansible.builtin.include_tasks:
    file: locale.yaml
    apply:
      tags: locale

- name: Configure network
  tags: network
  block:
    - name: Configure system network
      tags: system
      ansible.builtin.include_tasks:
        file: network/system.yaml
        apply:
          tags:
            - system
            - network

    - name: Configure systemd-resolved
      tags: resolved
      ansible.builtin.include_tasks:
        file: network/resolved.yaml
        apply:
          tags:
            - resolved
            - network

    - name: Configure Network Manager
      tags: manager
      ansible.builtin.include_tasks:
        file: network/manager.yaml
        apply:
          tags:
            - manager
            - network

- name: Configure initial ramdisk
  tags: initramfs
  ansible.builtin.include_tasks:
    file: initramfs.yaml
    apply:
      tags: initramfs

- name: Configure root user
  tags: root
  ansible.builtin.include_tasks:
    file: root.yaml
    apply:
      tags: root

- name: Configure sshd
  tags: sshd
  ansible.builtin.include_tasks:
    file: sshd.yaml
    apply:
      tags: sshd

- name: Configure boot loader
  tags: boot
  ansible.builtin.include_tasks:
    file: boot.yaml
    apply:
      tags: boot
