---
- name: Install packages
  loop: "{{ config_package_list | reject('equalto', omit) }}"
  ansible.builtin.package:
    name: "{{ item }}"

- name: Install pip modules
  loop: "{{ config_package_pip_list }}"
  ansible.builtin.pip:
    name: "{{ item }}"
    break_system_packages: true
