---
# User account name.
user_name: "{{ undef(hint='You must specify a user name') }}"

# User account password.
user_password: "{{ undef(hint='You must specify a user password') }}"

# System groups assigned to the user.
user_groups:
  - adm
  - games
  - sys
  - uucp
  - wheel
  - "{{ 'docker' if 'docker' in ansible_facts.packages else omit }}"
  - "{{ 'libvirt' if 'libvirt' in ansible_facts.packages else omit }}"

# SSH public keys for remote login.
user_ssh_keys: []

# Storage mode for the home directory.
user_storage: luks

# When LUKS2 storage is used configures whether to enable the "discard" feature of the file system.
user_storage_luks_discard: true

# Controls what happens when the home directory becomes inactive.
user_storage_luks_offline_discard: true

# Filesystem type used for the user's home directory.
user_filesystem: btrfs

# Size of the disk allocated for the user's home directory.
user_disk_size: "{{ '24G' if user_storage == 'luks' else 'max' }}"

# Login shell for the user.
user_shell: /usr/bin/fish
