---
- name: Set system hostname
  vars:
    common_managed_content: "{{ config_network_system_hostname }}"
  ansible.builtin.template:
    src: "{{ common_template_managed_local_path }}"
    dest: /etc/hostname
    mode: "0644"
    owner: root
    group: root

- name: Write system hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
    owner: root
    group: root

- name: Enable Bluetooth
  ansible.builtin.systemd_service:
    name: bluetooth
    state: started
    enabled: true
