---
# Name of the main LVM volume group used across the system.
partition_lvm_group_name: "{{ undef(hint='You must specify the name of the main LVM volume group') }}"

# LVM volume groups with associated devices.
partition_lvm_groups:
  - name: "{{ partition_lvm_group_name }}"
    devices:
      - "{{ (partition_layout_device, 2) | join_device_partition }}"

# LVM volumes for UEFI systems.
partition_lvm_volumes_uefi:
  - name: boot
    size: 512M
  - name: root
    size: 16G
  - name: var
    size: 8G
  - name: log
    size: 512M
  - name: home
    size: 32G
  - name: games
    size: 4G
  - name: swap
    size: 1G

# LVM volumes for BIOS systems.
partition_lvm_volumes_bios:
  - name: root
    size: 16G
  - name: var
    size: 8G
  - name: log
    size: 512M
  - name: home
    size: 32G
  - name: games
    size: 4G
  - name: swap
    size: 1G

# Boot-mode-specific LVM volume list.
partition_lvm_volumes: "{{ partition_lvm_volumes_uefi if common_boot_mode_uefi else partition_lvm_volumes_bios }}"

# Filesystems for BIOS LVM volumes.
partition_lvm_filesystems_bios:
  - name: root
    type: ext4
  - name: var
    type: xfs
  - name: log
    type: xfs
  - name: home
    type: btrfs
  - name: games
    type: ext4
  - name: swap
    type: swap

# Filesystems for UEFI LVM volumes.
partition_lvm_filesystems_uefi:
  - name: boot
    type: ext2
  - name: root
    type: ext4
  - name: var
    type: xfs
  - name: log
    type: xfs
  - name: home
    type: btrfs
  - name: games
    type: ext4
  - name: swap
    type: swap

# Boot-mode-specific LVM filesystem list.
partition_lvm_filesystems: "{{ partition_lvm_filesystems_uefi if common_boot_mode_uefi else partition_lvm_filesystems_bios }}"
