---
# Device that is mounted as the root filesystem.
config_boot_root_partition: "{{ config_boot_root_partition_result.stdout }}"

# Device that is mounted as the boot filesystem.
config_boot_partition: "{{ config_boot_partition_result.stdout }}"

# Parent disk device for the boot partition.
config_boot_device: "{{ config_boot_partition | parent_device }}"

# Mount point for the EFI System Partition.
config_boot_efi_dir: /efi

# Identifier used for the EFI boot entry.
config_boot_efi_id: GRUB

# Content for drop-in bootloader config files.
config_boot:
  root: GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 root={{ config_boot_root_partition }}"
  modules: GRUB_PRELOAD_MODULES="{{ config_boot_partition_module }} lvm"
