---
# Device that is mounted as the root filesystem.
config_boot_root_partition: "{{ config_boot_root_partition_result.stdout }}"

# Device that is mounted as the boot filesystem.
config_boot_partition: "{{ config_boot_partition_result.stdout }}"

# Parent disk device for the boot partition.
config_boot_device: "{{ config_boot_partition | parent_device }}"

# Mount point for the EFI System Partition.
config_boot_efi_dir: /efi

# Identifier used for the EFI boot entry.
config_boot_efi_id: GRUB

# Content for drop-in bootloader config files.
config_boot:
  root: |
    GRUB_CMDLINE_LINUX_DEFAULT="quiet splash loglevel=3 systemd.show_status=auto rd.udev.log_level=3 vt.global_cursor_default=0 root={{ config_boot_root_partition }}"
  timeout: |
    GRUB_TIMEOUT="0"
    GRUB_TIMEOUT_STYLE="hidden"
  modules: |
    GRUB_PRELOAD_MODULES="{{ config_boot_partition_module }} lvm"

# List of replacement rules to apply to the GRUB config.
config_boot_patches:
  # Remove 'Loading...' messages.
  - regexp: '^(?!#)(.*\becho\b.*)$'
    replace: '# \1'
