---
# Path to the common role.
common_role_local_dir: "{{ (role_path, '../common') | ansible.builtin.path_join | ansible.builtin.realpath }}"

# Path to its vars' directory.
common_variable_local_dir: "{{ (common_role_local_dir, 'vars') | ansible.builtin.path_join }}"

# Path to its templates' directory.
common_template_local_dir: "{{ (common_role_local_dir, 'templates') | ansible.builtin.path_join }}"

# Path to managed.j2 template.
common_template_managed_local_path: "{{ (common_template_local_dir, 'managed.j2') | ansible.builtin.path_join }}"

# Maps raw CPU vendor strings to simplified names.
common_cpu_vendor_map:
  AuthenticAMD: amd
  GenuineIntel: intel

# Normalized CPU vendor name based on detected processor.
common_cpu_vendor: "{{ common_cpu_vendor_map.get(ansible_processor[1], 'unknown') }}"

# Maps raw GPU vendor strings to simplified names.
common_gpu_vendor_map:
  "Intel Corporation": intel
  "NVIDIA Corporation": nvidia
  "Advanced Micro Devices, Inc. [AMD/ATI]": amd

# Parsed lshw display info.
common_display_info_json: "{{ (common_display_info_result.stdout) | ansible.builtin.from_json }}"

# Normalized GPU vendor name based on lshw display info.
common_gpu_vendor: "{{ common_gpu_vendor_map.get(common_display_info_json[0].vendor, 'unknown') }}"

# True if the system was booted in UEFI mode.
common_boot_mode_uefi: "{{ common_uefi_path_info_result.stat.exists }}"

# Header of managed templates.
common_managed_header: >-
  {% if template_path != common_template_managed_local_path %}
  Managed by Ansible | Template: {{ template_path }} (last modified: {{ template_mtime.strftime('%Y-%m-%d %H:%M:%S') }})
  {% else %}
  Managed by Ansible
  {% endif %}
