---
- name: Configure disk layout
  tags: layout
  ansible.builtin.include_tasks:
    file: layout.yaml
    apply:
      tags: layout

- name: Configure LVM
  tags: lvm
  ansible.builtin.include_tasks:
    file: lvm.yaml
    apply:
      tags: lvm

- name: Configure mount points
  tags: mount
  ansible.builtin.include_tasks:
    file: mount.yaml
    apply:
      tags: mount
