---
- name: Configure partition table
  tags: table
  ansible.builtin.include_tasks:
    file: table.yaml
    apply:
      tags: table

- name: Configure filesystems
  tags: filesystem
  ansible.builtin.include_tasks:
    file: filesystem.yaml
    apply:
      tags: filesystem
