---
# Mapping of GPU vendors to appropriate DRI (Direct Rendering Infrastructure) packages.
config_package_dri_map:
  amd: mesa
  intel: mesa
  nvidia: nvidia-open

# Mapping of GPU vendors to Vulkan driver packages.
config_package_vulkan_map:
  amd: vulkan-radeon
  intel: vulkan-intel
  nvidia: nvidia-utils
